"""Deterministic synthetic fixtures for the stub provider.

DISCLAIMER: none of this is real market data. Every record is tagged
``source="STUB_FIXTURE"``. Series are generated by a fixed formula (no RNG) so
runs are byte-for-byte reproducible. A "no data" symbol returns an EMPTY list —
the stub never fabricates a bar to fill a gap (docs/09 §2.5).
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal

from analytical_core.enums import InstrumentType, OptionType, Timeframe
from app.providers.base import STUB_SOURCE, InstrumentRecord, OHLCVBar, OISnapshot

FIXTURE_DISCLAIMER = "SYNTHETIC PHASE-1 FIXTURE — NOT REAL MARKET DATA"

# --- instrument master ------------------------------------------------------

STUB_INSTRUMENTS: tuple[InstrumentRecord, ...] = (
    InstrumentRecord(
        provider="stub",
        provider_symbol="STUB:NIFTY-INDEX",
        instrument_type=InstrumentType.INDEX,
        underlying_symbol=None,
        exchange="NSE",
        display_name="NIFTY 50 (synthetic)",
        source=STUB_SOURCE,
        raw={"disclaimer": FIXTURE_DISCLAIMER},
    ),
    InstrumentRecord(
        provider="stub",
        provider_symbol="STUB:BANKNIFTY-INDEX",
        instrument_type=InstrumentType.INDEX,
        underlying_symbol=None,
        exchange="NSE",
        display_name="NIFTY BANK (synthetic)",
        source=STUB_SOURCE,
        raw={"disclaimer": FIXTURE_DISCLAIMER},
    ),
    InstrumentRecord(
        provider="stub",
        provider_symbol="STUB:NIFTY-FUT-NEAR",
        instrument_type=InstrumentType.FUTURE,
        underlying_symbol="STUB:NIFTY-INDEX",
        exchange="NSE",
        expiry_date=datetime(2026, 9, 24, tzinfo=UTC).date(),
        lot_size=50,
        tick_size=Decimal("0.05"),
        display_name="NIFTY FUT near (synthetic)",
        source=STUB_SOURCE,
        raw={"disclaimer": FIXTURE_DISCLAIMER},
    ),
    InstrumentRecord(
        provider="stub",
        provider_symbol="STUB:NIFTY-OPT-24000-CE",
        instrument_type=InstrumentType.OPTION,
        underlying_symbol="STUB:NIFTY-INDEX",
        exchange="NSE",
        expiry_date=datetime(2026, 9, 4, tzinfo=UTC).date(),
        strike_price=Decimal("24000"),
        option_type=OptionType.CE,
        lot_size=50,
        tick_size=Decimal("0.05"),
        display_name="NIFTY 24000 CE (synthetic)",
        source=STUB_SOURCE,
        raw={"disclaimer": FIXTURE_DISCLAIMER},
    ),
    InstrumentRecord(
        provider="stub",
        provider_symbol="STUB:NIFTY-OPT-24000-PE",
        instrument_type=InstrumentType.OPTION,
        underlying_symbol="STUB:NIFTY-INDEX",
        exchange="NSE",
        expiry_date=datetime(2026, 9, 4, tzinfo=UTC).date(),
        strike_price=Decimal("24000"),
        option_type=OptionType.PE,
        lot_size=50,
        tick_size=Decimal("0.05"),
        display_name="NIFTY 24000 PE (synthetic)",
        source=STUB_SOURCE,
        raw={"disclaimer": FIXTURE_DISCLAIMER},
    ),
)

STUB_SYMBOLS: tuple[str, ...] = tuple(r.provider_symbol for r in STUB_INSTRUMENTS)

_TF_MINUTES: dict[Timeframe, int] = {
    Timeframe.M1: 1,
    Timeframe.M5: 5,
    Timeframe.M15: 15,
    Timeframe.H1: 60,
    Timeframe.D1: 24 * 60,
}


def _base_price(symbol: str) -> Decimal:
    return Decimal(str(1000 + (abs(hash(symbol)) % 9000)))


def stub_ohlcv(
    symbol: str, timeframe: Timeframe, start: datetime, end: datetime, *, count: int = 12
) -> list[OHLCVBar]:
    """A short deterministic synthetic series. Formula-based, no randomness."""
    step = timedelta(minutes=_TF_MINUTES[timeframe])
    base = _base_price(symbol)
    bars: list[OHLCVBar] = []
    ts = start
    for i in range(count):
        if ts >= end:
            break
        drift = Decimal(i) * Decimal("0.25")
        o = base + drift
        h = o + Decimal("1.5")
        low = o - Decimal("1.0")
        c = o + Decimal("0.5")
        bars.append(
            OHLCVBar(
                ts=ts,
                open=o,
                high=h,
                low=low,
                close=c,
                volume=100 + i,
                is_final=(i < count - 1),
                source=STUB_SOURCE,
            )
        )
        ts = ts + step
    return bars


def stub_oi_snapshot(symbol: str, at: datetime) -> OISnapshot:
    base_oi = 10_000 + (abs(hash(symbol)) % 5_000)
    return OISnapshot(
        snapshot_ts=at,
        oi=base_oi,
        provider_oi_change=None,
        day_volume=12_345,
        instrument_price=_base_price(symbol),
        source=STUB_SOURCE,
    )
